### ISSUE TITLE
Release mode perfect but debug mode failed

### ISSUE THREAD

**Issue by breadli428** [cmm-21/a2#7] opened 2021-03-19 15:46 UTC
Hi,

I finished ex 2.2 and it worked perfectly under release mode, however the green ball indicators as well as the feet do not move (trot) when I run it under the debug mode.

Is this normal?

Thanks!

**Comment by eastskykang** [comment] 2021-03-19 16:13
@breadli428 Hi,

Does the app freeze (and don't respond at all)?

**Comment by breadli428** [comment] 2021-03-19 16:17
Not freeze. I can rotate the scene,  I can click the play button and the yellow dots depicting the feet trajectories move as normal. But the green dots and the feet won’t move at all.

**Comment by eastskykang** [comment] 2021-03-20 15:41
I will test this on my Windows machine and come back as soon as possible.

**Comment by eastskykang** [comment] 2021-03-20 18:36
Unfortunately, I couldn't reproduce this problem on my Windows machine. Can we discuss this problem in the next tutorial session (on 25th of March)?

**Comment by breadli428** [comment] 2021-03-20 19:26
Sure! Thanks Dongho!

**Comment by eastskykang** [comment] 2021-03-29 00:17
#33 @breadli428 can you quickly try this and let me know if this issue is still there or not?

**Comment by breadli428** [comment] 2021-03-31 09:05
Hi Dongho,

I tried and it seems that the problem is solved, though it runs really slow. It barely moves, but on a right track.

Thanks a lot!

**Comment by eastskykang** [comment] 2021-03-31 09:22
@breadli428 awesome! It's super normal to be slow in debug mode :)

I will close this issue now.

**Closed as completed by eastskykang** 2021-03-31 09:22 UTC
